---
Name: coreconfig
---
SilverStripe\Control\HTTP:
  cache_control:
    no-cache: true
    no-store: true
    must-revalidate: true
  vary: "X-Requested-With, X-Forwarded-Protocol"
SilverStripe\Core\Manifest\VersionProvider:
  modules:
    silverstripe/framework: Framework
---
Name: httpconfig-dev
Only:
  environment: dev
---
SilverStripe\Control\HTTP:
  disable_http_cache: true
